BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Togstasjon" (
	"StasjonsNavn"	TEXT NOT NULL,
	"Moh"	INTEGER,
	PRIMARY KEY("StasjonsNavn")
);
CREATE TABLE IF NOT EXISTS "Banestrekning" (
	"BaneNavn"	TEXT NOT NULL,
	"Fremdriftenergi"	TEXT,
	"StartStasjon"	TEXT NOT NULL,
	"SluttStasjon"	TEXT NOT NULL,
	FOREIGN KEY("SluttStasjon") REFERENCES "Togstasjon"("StasjonsNavn") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("BaneNavn"),
	FOREIGN KEY("StartStasjon") REFERENCES "Togstasjon"("StasjonsNavn") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Operatoer" (
	"OperatoerNavn"	TEXT NOT NULL,
	PRIMARY KEY("OperatoerNavn")
);
CREATE TABLE IF NOT EXISTS "Togtur" (
	"RuteID"	INTEGER NOT NULL,
	"Dato"	TEXT NOT NULL,
	PRIMARY KEY("RuteID","Dato"),
	FOREIGN KEY("RuteID") REFERENCES "Togrute"("RuteID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Delstrekning" (
	"StrekningNavn"	TEXT NOT NULL,
	"Lengde"	INTEGER,
	"AntallSpor"	INTEGER,
	"Hovedretning"	TEXT,
	"MotHovedretning"	TEXT,
	"StartStasjon"	TEXT NOT NULL,
	"SluttStasjon"	TEXT NOT NULL,
	PRIMARY KEY("StrekningNavn"),
	FOREIGN KEY("Hovedretning") REFERENCES "Banestrekning"("BaneNavn") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("StartStasjon") REFERENCES "Togstasjon"("StasjonsNavn") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("SluttStasjon") REFERENCES "Togstasjon"("StasjonsNavn") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("MotHovedretning") REFERENCES "Banestrekning"("BaneNavn") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "VognType" (
	"VognNavn"	TEXT NOT NULL,
	"OperatoerNavn"	TEXT NOT NULL,
	PRIMARY KEY("VognNavn")
);
CREATE TABLE IF NOT EXISTS "SoveVogn" (
	"VognNavn"	TEXT NOT NULL,
	"AntallSoveKupeer"	INTEGER,
	"AntallSenger"	INTEGER,
	PRIMARY KEY("VognNavn"),
	FOREIGN KEY("VognNavn") REFERENCES "VognType"("VognNavn") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "SitteVogn" (
	"VognNavn"	TEXT NOT NULL,
	"AntallSeter"	INTEGER,
	"AntallRader"	INTEGER,
	PRIMARY KEY("VognNavn"),
	FOREIGN KEY("VognNavn") REFERENCES "VognType"("VognNavn") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "KundeOrdre" (
	"OrdreNr"	INTEGER NOT NULL,
	"Tidspunkt"	TEXT,
	"Dato"	TEXT,
	"KundeNr"	INTEGER NOT NULL,
	PRIMARY KEY("OrdreNr" AUTOINCREMENT),
	FOREIGN KEY("KundeNr") REFERENCES "Kunde"("KundeNr") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Dager" (
	"RuteID"	INTEGER NOT NULL,
	"Dag"	TEXT NOT NULL,
	PRIMARY KEY("RuteID","Dag"),
	FOREIGN KEY("RuteID") REFERENCES "Togrute"("RuteID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "KjoererDelstrekning" (
	"RuteID"	INTEGER NOT NULL,
	"StrekningNavn"	TEXT NOT NULL,
	"AvgangsTid"	TEXT,
	"AnkomstTid"	TEXT,
	PRIMARY KEY("RuteID","StrekningNavn"),
	FOREIGN KEY("StrekningNavn") REFERENCES "Delstrekning"("StrekningNavn") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("RuteID") REFERENCES "Togrute"("RuteID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Sete" (
	"SeteNr"	INTEGER NOT NULL,
	"VognNr"	INTEGER NOT NULL,
	"RuteID"	INTEGER NOT NULL,
	PRIMARY KEY("SeteNr","VognNr","RuteID"),
	FOREIGN KEY("RuteID") REFERENCES "Vogn"("RuteID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("VognNr") REFERENCES "Vogn"("VognID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Vogn" (
	"VognNr"	INTEGER NOT NULL,
	"RuteID"	INTEGER NOT NULL,
	"VognNavn"	TEXT NOT NULL,
	FOREIGN KEY("RuteID") REFERENCES "Togrute"("RuteID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("VognNavn") REFERENCES "VognType"("VognNavn") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("VognNr","RuteID")
);
CREATE TABLE IF NOT EXISTS "Seng" (
	"SengNr"	INTEGER NOT NULL,
	"VognNr"	INTEGER NOT NULL,
	"RuteID"	INTEGER NOT NULL,
	"KupeNr"	INTEGER,
	FOREIGN KEY("VognNr") REFERENCES "Vogn"("VognNr") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("RuteID") REFERENCES "Vogn"("RuteID") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("SengNr","VognNr","RuteID")
);
CREATE TABLE IF NOT EXISTS "Kunde" (
	"KundeNr"	INTEGER NOT NULL,
	"Navn"	TEXT,
	"E-post"	TEXT UNIQUE,
	"TelefonNr"	INTEGER UNIQUE,
	PRIMARY KEY("KundeNr" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Togrute" (
	"RuteID"	INTEGER NOT NULL,
	"Navn"	TEXT,
	"OperatoerNavn"	TEXT NOT NULL,
	FOREIGN KEY("OperatoerNavn") REFERENCES "Operatoer"("OperatoerNavn") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("RuteID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Billett" (
	"BillettNr"	INTEGER NOT NULL,
	"OrdreNr"	INTEGER,
	"VognNr"	INTEGER NOT NULL,
	"RuteID"	INTEGER NOT NULL,
	"SengNr"	INTEGER,
	"SeteNr"	INTEGER,
	"TogTurID"	INTEGER NOT NULL,
	"TogTurDato"	TEXT NOT NULL,
	"StrekningNavn"	TEXT NOT NULL,
	FOREIGN KEY("SengNr") REFERENCES "Seng"("SengNr") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("StrekningNavn") REFERENCES "Delstrekning"("StrekningNavn") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("SeteNr") REFERENCES "Sete"("SeteNr") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("TogTurID") REFERENCES "Togtur"("RuteID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("VognNr") REFERENCES "Vogn"("VognID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("TogTurDato") REFERENCES "Togtur"("Dato") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("OrdreNr") REFERENCES "KundeOrdre"("OrdreNr") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("RuteID") REFERENCES "Vogn"("VognNr") ON UPDATE CASCADE,
	PRIMARY KEY("BillettNr" AUTOINCREMENT)
);

COMMIT;
